reddit_clone/config/routes.rb
Rails.application.routes.draw do

  resources :subs, except: [:destroy]
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :PostSub

  has_many :posts,
    through: :post_subs,
    source: :post
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_logged_in, only: [:new, :create, :edit, :update]
  before_action :ensure_sub_owner, only: [:edit, :update]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub && @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def index
    @subs = Sub.all
    render :index
  end

  def ensure_sub_owner
    @sub = current_user.subs.find(params[:id])
    if @sub
      true
    else
      flash[:errors] = ["You're not the owner of this sub"]
      redirect_to sub_url(params[:id])
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">
  <label for="title">Title: </label>
  <input id="title" type="text" name="sub[title]" value="<%= @sub.title %>">
  <br>
  <br>
  <label for="description">Description: </label>
  <textarea id="description" name="sub[description]"><%= @sub.description %></textarea>
  <br>
  <input type="submit" name="" value="Update Sub">
</form>

reddit_clone/app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
  <% @subs.each do |s| %>
  <li>
    <%= link_to s.title, sub_url(s) %>
  </li>
  <% end %>
</ul>

reddit_clone/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="title">Title: </label>
  <input id="title" type="text" name="sub[title]" value="<%= @sub.title %>">
  <br>
  <br>
  <label for="description">Description: </label>
  <textarea id="description" name="sub[description]"><%= @sub.description %></textarea>
  <br>
  <input type="submit" name="" value="Create Sub">
</form>

reddit_clone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p>Description: <%= @sub.description %></p>
<%= button_to "Edit Link", edit_sub_url(@sub), method: :get%>