reddit_clone/config/routes.rb
Rails.application.routes.draw do

  resources :subs, except: [:destroy]
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit_clone/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  content          :text             not null
#  commentable_type :string
#  commentable_id   :integer
#  author_id        :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :commentable, polymorphic: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  def find_post_id
    return commentable_id if commentable_type == 'Post'
    self.commentable.find_post_id
  end

end

reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    @comment.commentable = @post
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id

    if params[:post_id]
      @comment.commentable = Post.find(params[:post_id])
    else
      @comment.commentable = Comment.find(params[:parent_comment_id])
    end

    if @comment.save
      redirect_to post_url(@comment.find_post_id)
    else
      flash.now[:errors] = @comment.errors.full_messages
      if @comment.commentable_type == 'Post'
        render :new
      else
        ##render back to parent comment
      end
    end
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

reddit_clone/app/helpers/comments_helper.rb
module CommentsHelper
end

reddit_clone/app/views/comments/new.html.erb
<h1>New Comment</h1>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="post_id" value="<%= @comment.commentable_id if @comment.commentable_type == 'Post' %>">
  <input type="hidden" name="parent_comment_id" value="<%= @comment.commentable_id if @comment.commentable_type == 'Comment' %>">
  <label for="content">Content: </label>
  <textarea id="content" name="comment[content]"><%=@comment.content%></textarea>
  <br>
  <br>
  <input type="submit" name="" value="Add Comment">
</form>